### ISSUE TITLE
Database location and output format

### ISSUE THREAD

**Issue by susheelbhanu** [bhattlab/SmORFinder#1]
Hey @durrantmm, 

Thanks for putting this up. Is there a way to specify the path to the database in the command line itself? I want to run the tool in a different folder from where it was set up and can't seem to find this option. 

Also, could you please provide an example of the expected output folder/file(s)?

Thank you,
Susheel

**Comment by durrantmm** [comment]
This should not be a problem, it can keep track of the path to the database after installation. How did you install it?

**Comment by susheelbhanu** [comment]
I want to include it as part of a snakemake pipeline via a conda yaml file, so had to make sure that the database location won't be an issue.

And is there a way to name the output folders?

**Comment by durrantmm** [comment]
I am not familiar with conda tank files, but I don't think it will be an issue if you install via `pip install smorfinder`.

If you want to be on the safe side, you can specify the paths to specific databases using:

        -pp, --prodigal-path PATH
        -shp, --dsn1-model-path PATH
        -shp, --dsn2-model-path PATH
        -shp, --smorf-hmm-path PATH
        -hp, --hmmsearch-path PATH

You can specify the output directory with `--outdir`

I hope that helps!

**Comment by durrantmm** [comment]
Also, be sure to run `smorf` at least once so it can download the required data.

**Comment by susheelbhanu** [comment]
Oops sorry. Autocorrect changed yaml to tank. But yes, I've downloaded the databases, and thanks a lot for the flags.

**Comment by durrantmm** [comment]
I wanted to double check, what version of smorfinder are you using? To check the version, open up a python prompt:

        python

And then import the version

       import smorfinder
       print(smorfinder.__version__)

It should be 0.0.3.dev0.

**Comment by susheelbhanu** [comment]
This is what I have.
```
>>> import smorfinder
>>> print(smorfinder.__version__)
0.0.3_dev
```

**Comment by durrantmm** [comment]
Great! Good luck, let me know if you have any more questions.

**Comment by susheelbhanu** [comment]
Thanks again and good luck to you as well!
