### ISSUE TITLE
DB Server Down?

### ISSUE THREAD

**Issue by tokeru** [bhattlab/SmORFinder#5]
I cannot access the Database Server. Looks like it is down.

Best
Alex

PS: tried to run it locally then with Error "OSError: [WinError 193] %1 is not a valid Win32 application". But iI guess this is some python issue here.

**Comment by durrantmm** [comment]
Sorry about that, working on the server. SmORFinder isn't compatible with windows. Please try Mac or Linux if you can.

**Comment by durrantmm** [comment]
Ok, it should be up and running now, sorry about that!
