### ISSUE TITLE
Pinned version of tensorflow no longer available

### ISSUE THREAD

**Issue by bsiranosian** [bhattlab/SmORFinder#9]
In the setup.py file and the pip install candidate, tensorflow==2.3.1 is no  longer available. I was able to get this to install by removing the pinned version.

**Comment by bsiranosian** [comment]
A functioning singularity image can be found here if anyone needs it:
`library://bsiranos/metagenomics/smorfinder:latest`

**Comment by aemiol** [comment]
> A functioning singularity image can be found here if anyone needs it: `library://bsiranos/metagenomics/smorfinder:latest`

Hi, I am unable to download the singularity image.
Thanks!

**Comment by bsiranosian** [comment]
Hi @aemiol, I can still pull this image without issue, nothing has changed. 

![image](https://user-images.githubusercontent.com/6730408/167305256-abff4ea5-1cdf-4f10-9055-20a26a7f09e8.png)
